nfs_server_ip: ""
nfs_export_path: ""
nfs_mount_path: ""

# 설치할 containerd 버전 (미지정 시 latest)
containerd_version_ubuntu: "1.7.24-1"
containerd_version_rocky: "1.6.32-3.1.el8"

# NOTE: 마이너 버전까지만 작성합니다.
k8s_version: "v1.30"
# NOTE: 컨트롤플레인 노드(마스터노드)에서 kubeadm token create --print-join-command 명령을 실행하여 출력된 내용을 붙여넣습니다.
k8s_join_command: "kubeadm join <controlplane ip>:<kube api server port> --token xxxxx --discovery-token-ca-cert-hash sha256:xxxxx"
# NOTE: k8s 노드들이 속한 네트워크의 CIDR 범위를 설정합니다.
k8s_cluster_cidr: "1.2.3.4/24"
